INSERT INTO CATEGORY (NAME) VALUES ('shoebase');
INSERT INTO CATEGORY (NAME) VALUES ('shoebody');
INSERT INTO CATEGORY (NAME) VALUES ('shoelaces');
INSERT INTO CATEGORY (NAME) VALUES ('logos');

INSERT INTO ITEM (NAME, CATEGORY) VALUES ('white shoebase', 1);
INSERT INTO ITEM (NAME, CATEGORY) VALUES ('black shoebase', 1);
INSERT INTO ITEM (NAME, CATEGORY) VALUES ('green body', 2);
INSERT INTO ITEM (NAME, CATEGORY) VALUES ('brown body', 2);
INSERT INTO ITEM (NAME, CATEGORY) VALUES ('lime shoelace', 3);
INSERT INTO ITEM (NAME, CATEGORY) VALUES ('black shoelace', 3);
INSERT INTO ITEM (NAME, CATEGORY) VALUES ('xmas tree logo', 4);
INSERT INTO ITEM (NAME, CATEGORY) VALUES ('banana logo', 4);

INSERT INTO ITEM_DEPENDENCY (DEPENDER, DEPENDEE) VALUES (7, 4);
INSERT INTO ITEM_DEPENDENCY (DEPENDER, DEPENDEE) VALUES (8, 3);