INSERT INTO CATEGORY (NAME, ORDERING) VALUES ('shoebase', 1);
INSERT INTO CATEGORY (NAME, ORDERING) VALUES ('shoelaces', 2);
INSERT INTO CATEGORY (NAME, ORDERING) VALUES ('logos', 3);

INSERT INTO ITEM (NAME, CATEGORY) VALUES ('white shoebase', 1);
INSERT INTO ITEM (NAME, CATEGORY) VALUES ('black shoebase', 1);
INSERT INTO ITEM (NAME, CATEGORY) VALUES ('lime shoelace', 2);
INSERT INTO ITEM (NAME, CATEGORY) VALUES ('black shoelace', 2);
INSERT INTO ITEM (NAME, CATEGORY) VALUES ('tree logo', 3);
INSERT INTO ITEM (NAME, CATEGORY) VALUES ('banana logo', 3);

INSERT INTO ITEM_DEPENDENCY (DEPENDER, DEPENDEE) VALUES (1, 2);